### ISSUE TITLE
Kubernetes client configuration in cloud server

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/cloud#102]
For now, There are two kinds of kubernetes-client in the cloud server,  submitting job/rs with service account client, create secret use RBAC client. Shall we only use service account client or RBAC client?

**Comment by Yancey1989** [comment]
*user kubernetes client* will be conflicted with *global kubernetes client*, so this bug will cause some access error in cloud server like:

```bash
HTTP response body: User "user-A" cannot list jobs.batch in the namespace "user-B".
```

**Comment by typhoonzero** [comment]
- users have admin authority of their own namespace to
    - create user jobs
    - view user namespace resources
- paddlecloud use admin user to manage users
    - namespace creation
    - secrets creation
