### ISSUE TITLE
Send registration email to user after sign up

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/cloud#103]
Send registration email to the user after sign up. The email should contain paddlecloud introduction, usage docs, registered account, etc.

**Comment by wangkuiyi** [comment]
Just mark what I learned from that PR #150:

1.  Install mailx to send emails,
1. Our server calls Django's `send_mail` API to invoke mailx.

An example mailx command line sending to Gmail accounts is at here:  https://www.systutorials.com/1411/sending-email-from-mailx-command-in-linux-using-gmails-smtp/
