### ISSUE TITLE
Prepare demo trainer package

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/cloud#110]
1. Prepare public dataset from `paddle.v2.dataset`.
1. Prepare trainer package in `demo` directory.

**Comment by typhoonzero** [comment]
I've created https://github.com/PaddlePaddle/Paddle/issues/2298 in `Paddle` repo, this is more related in there.

Secondly, we need to make use of `book` and `models` repo to provide more demos, not copy them around.

**Comment by Yancey1989** [comment]
Thanks, @typhoonzero , I think we can run the demos of `book` repo in the first stage, this work including:

1. How to modify the `train.py` file in `book` repo, so it can run on PaddleCloud
- Implement the `split` and `cluster_files_reader` function as  https://github.com/PaddlePaddle/Paddle/issues/2298
- `train.py` should read the training data from the cluster files using `cluster_files_reader` function.

1. Prepare the public dataset
- Before deploying PaddleCloud, we should split all the dataset into cluster files and save them on CephFS or HDFS as the public dataset
- Trainer job should mount the public dataset directory into the Kubernetes Pod, so the trainer code will read the public dataset from `/pfs/$DC_NAME/public/$DATASET/$FILES`

**Comment by Yancey1989** [comment]
#122 is used for prepare public dataset.
