### ISSUE TITLE
fix the problem of go get

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/cloud#159]
package golang.org/x/net/context: unrecognized import path "golang.org/x/net/context" (https fetch: Get https://golang.org/x/net/context?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package golang.org/x/net/http2: unrecognized import path "golang.org/x/net/http2" (https fetch: Get https://golang.org/x/net/http2?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package cloud.google.com/go/compute/metadata: unrecognized import path "cloud.google.com/go/compute/metadata" (https fetch: Get https://cloud.google.com/go/compute/metadata?go-get=1: dial tcp 74.125.23.139:443: i/o timeout)

**Comment by jacquesqiao** [comment]
http://www.joomla178.com/joomla-share/research-and-development/651-how-to-install-gogs.html
```shell
git clone https://go.googlesource.com/crypto
git clone https://go.googlesource.com/net
git clone https://go.googlesource.com/text
```

**Comment by jacquesqiao** [comment]
new problem:
```
package cloud.google.com/go/compute/metadata: unrecognized import path "cloud.google.com/go/compute/metadata" (https fetch: Get https://cloud.google.com/go/compute/metadata?go-get=1: dial tcp 64.233.189.139:443: i/o timeout)
package golang.org/x/tools/go/buildutil: unrecognized import path "golang.org/x/tools/go/buildutil" (https fetch: Get https://golang.org/x/tools/go/buildutil?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

package golang.org/x/tools/go/loader: unrecognized import path "golang.org/x/tools/go/loader" (https fetch: Get https://golang.org/x/tools/go/loader?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
```

**Comment by typhoonzero** [comment]
Seems like a network failure? Try run `go get -u github.com/coreos/etcd/clientv3` to update all the packages.

**Comment by jacquesqiao** [comment]
Use VPN can solve this problem, f..k GFW.
