### ISSUE TITLE
Command line client for job management

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/cloud#16]
1. `paddlecloud submit ...`: submit a training job
1. `paddlecloud jobs [-a]`: list jobs, default list running jobs.
1. `paddlecloud quota`: show current quota usages
1. `paddlecloud pfs ...`: paddle cloud filesystem operations.

Write this in Go, so that we can build the client for MacOS/Linux/Windows.

I'll create a design doc for this.

**Comment by Yancey1989** [comment]
> paddlecloud submit ...: submit a training job

How about merge source code of https://github.com/PaddlePaddle/Job into the cloud repo, and provide a REST API which `paddlecloud submit` called.

**Comment by typhoonzero** [comment]
@Yancey1989 Agree!
