### ISSUE TITLE
关于调试脚本

### ISSUE THREAD

**Issue by pineking** [PaddlePaddle/cloud#198]
我看文档，paddlecloud submit 会直接上传 train.py  并默认运行，如果 train.py 没问题，运行很正常，比较方便。

如果 train.py 是用户新写的，需要多次来回调试，就需要多次 paddlecloud submit 和 paddlecloud kill ，是不是不大方便？有没有一次 submit 运行 sleep 10d，然后再调试 train.py ?

**Comment by Yancey1989** [comment]
> 我看文档，paddlecloud submit 会直接上传 train.py 并默认运行，如果 train.py 没问题，运行很正常，比较方便。

运行脚本的方式可以通过`-entry`参数来指定， 甚至可以`-entry sleep 3600`

**Comment by typhoonzero** [comment]
@pineking paddlecloud命令不提供类似`exec`的功能，train.py是可以本地调试的。

**Comment by pineking** [comment]
当指定 `-entry sleep 3600` 时，如何启动 train.py 开始调试, 需要类似 kubectl exec 进到容器里吗？

还有一个问题，train.py 是 copy 到容器内的目录，还是像数据一样，复制到 HDFS 之类的分布式存储中挂载到 container 中？

**Comment by pineking** [comment]
@typhoonzero 如果本地没数据或者 GPU，train.py 也可以调试？

**Comment by typhoonzero** [comment]
用少量数据和CPU也可以调试

**Comment by pineking** [comment]
@Yancey1989 @typhoonzero 明白了
