### ISSUE TITLE
Sometimes `paddlecloud logs` is delayed

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/cloud#256]
I can see the logs maybe 1min after the job completed, was expecting to see almost realtime logs.
Just curious why logs are very delayed?

Update: the first jobs have delayed log, the second job's logs looks fine.

**Comment by typhoonzero** [comment]
docker collect logs from stdout and since it is buffered the output is not "real time", will add `stdbuf -oL` to the start up script.
