### ISSUE TITLE
Build paddlecloud-job Docker image 

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/cloud#29]
Kubernetes Pod中不能直接PaddlePaddle product Docker image因为有几个脚本在PaddlePaddle中不存在: https://github.com/PaddlePaddle/Job/tree/develop/tools， 建议创建一个目录`./docker` 目录，来编译Cloud上运行的镜像，可以命名为`paddlecloud-job:0.10.0`, `paddlecloud-job:0.10.0-gpu`

**Comment by typhoonzero** [comment]
赞同。

需要编译的docker 镜像包括

- 运行v1 API的集群训练image(CPU, GPU)
- 运行v2 API的集群训练image(CPU, GPU)
- 运行book并可以提交kubernetes训练任务的image

**Comment by Yancey1989** [comment]
> - 运行v1 API的集群训练image(CPU, GPU)
> - 运行v2 API的集群训练image(CPU, GPU)


感觉这两个可以是同一个镜像
