### ISSUE TITLE
Cannot submit job when using hostPath 

### ISSUE THREAD

**Issue by m3ngyang** [PaddlePaddle/cloud#293]
When I tried to submit a job to the paddlecloud server, it returned 
```
➜  cloud paddlecloud submit -jobname fit-a-line -cpu 1 -gpu 1 -parallelism 1 -entry "python train.py" fit_a_line/
Uploading ... fit_a_line/train.py /pfs/mytest/home/t@t.com/jobs/fit-a-line/train.py
error submiting job: package not exist in cloud: fit_a_line/
```
Relative path doesn't work when paddlecloud uses hostPath as data-storage type.

**Comment by typhoonzero** [comment]
So which version of paddlecloud client are you using?

**Comment by m3ngyang** [comment]
@typhoonzero the latest version, v0.1.1-beta.3

**Comment by typhoonzero** [comment]
Accroding to `/pfs/mytest/home/t@t.com/jobs/fit-a-line/train.py` seems like you misconfigured the datacenter and username? I've tested with the macos binary which succeeded.
