### ISSUE TITLE
存储选型Ceph VS. HDFS

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/cloud#3]
特性|HDFS| CephFS
--- | --- | ---
MapReduce支持|原生支持|插件支持[cephfs-hadoop](https://github.com/ceph/cephfs-hadoop)，hadoop 2.7.1
Kubernetes支持|不支持，需开发Kubernetes插件|社区支持
稳定性|好|高可用有风险（metadata server切换会卡顿，对读写延迟有影响）
认证|弱|弱
系统要求|安装JDK即可|CentOS7以上（CephFS在J版本是production ready，而J版本要CentOS7）或者在CentOS6上用Docker部署
小文件性能|差|可对小文件优化
安全|不建议公网暴露接口|不建议公网暴露接口

**Comment by typhoonzero** [comment]
看起来CephFS对kubernetes和运行hadoop job都有支持。对于可用性风险，paddle cloud目前主要针对离线训练场景。对于在线场景的存储也可以直接使用ceph RBD(可以和cephfs作为同一个集群)。

建议使用新版的CephpFS

**Comment by wangkuiyi** [comment]
如果不行，咱们再退一步，有步可退不？

**Comment by Yancey1989** [comment]
Ceph在CentOS6上只能基于Docker部署，或许单独启一个docker engine，在上面启动ceph container，并且使用本机的网卡可以规避一些风险。

CephFS+1

**Comment by typhoonzero** [comment]
备选方案（HDFS之外）：

1. 使用ceph RBD，trainer0挂载存储输出模型，其他的pod直接输出到容器中。
1.. 集群中增加一个硬件存储设备（一般这个设备上会提供nfs服务），k8s使用nfs挂载这个存储设备的数据。

**Comment by pineking** [comment]
GlusterFS 没有 MDS ( metadata server )，ls 的时候会遍历所有文件，如果目录层次很深的话，性能会受到很大影响

我们现在换成用 Lustre 了，缺点是和 kernel 紧密相关

**Comment by typhoonzero** [comment]
CephFS和HDFS后续根据实际需求使用，目前看这两个文件系统都有使用的场景。优先选择使用CephFS
