### ISSUE TITLE
PaddleCloud 大文件上传失败

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/cloud#308]
用`paddlecloud cp` 上传59G大小的文件，出现`error bad file size`错误。

**Comment by gongweibao** [comment]
程序中限定的，最大4G

**Comment by typhoonzero** [comment]
是pfsclient本身做的限定么？

**Comment by gongweibao** [comment]
https://github.com/PaddlePaddle/cloud/issues/309
