### ISSUE TITLE
paddlecloud need `quick start` job & traning data

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/cloud#311]
用户将得到：
- 对`paddlecloud`有一个快速的印象，即使用户的任务还没准备好；
- 如果我自己有一个任务，我可以参考来修改；
- 借助这个quick job熟悉一下命令（submit\logs\kill）;
- 这个平台当前是否可用？如果出现了问题应该是任务代码问题，不是平台问题；

**Comment by typhoonzero** [comment]
https://github.com/PaddlePaddle/cloud/blob/develop/doc/tutorial_cn.md
这个其实就是quick_start。

> 这个平台当前是否可用？如果出现了问题应该是任务代码问题，不是平台问题；

可以在FAQ中增加这些文档。

**Comment by llxxxll** [comment]
确实是，之前读的usage_cn.md，感谢！
