### ISSUE TITLE
上传超大文件的时候超时

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/cloud#313]
### 问题描述：上传1.2G文件，偶尔出现：
```
 error server error: 504 Gateway Time-out
&errors.errorString{s:"server error: 504 Gateway Time-out"}
```

### 问题复现：
测试上传超大文件72G，稳定复现

### 问题原因分析：
现在上传(或者下载)文件之前，为了只传输diff，先要把server端文件按照块大小虚拟分块，然后把整个文件读一遍同时把每个分块hash值计算一遍。读数据和计算hash(现在用的md5值）都(1.2G已经需要计算512次)需要耗费不短的时间。而ingerss和service之间的超时一般只有60秒。

### 问题解决方式：
不读整个文件，而是只读需要的块(seek)，只计算该块的hash值。这样应该不会有超时的问题了。

**Comment by gongweibao** [comment]
感谢 @xinghai-sun 帮忙发现的问题！

**Comment by xinghai-sun** [comment]
Great! Thanks!

**Comment by helinwang** [comment]
@gongweibao 是recordio文件吗？能否生成的时候就converter自动分成很多小块shard(xxxxx-of-yyyyy)？

**Comment by gongweibao** [comment]
不一定是什么格式的文件
估计还是避免不了大文件的问题。1.2g其实不算大。

**Comment by helinwang** [comment]
嗯，1.2G确实不大。
我们可以鼓励用户传recordio作为训练格式，因为可容错只支持recordio。
