### ISSUE TITLE
non-fault-tolerant: trainer ID started with 1, rather than 0

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/cloud#318]
I think we need to make it starting from 0.

**Comment by Yancey1989** [comment]
With the logic: https://github.com/PaddlePaddle/cloud/blob/develop/docker/k8s_tools.py#L53, trainer ID is start with 0, maybe some other bug cause this situation? how can I reproduce the situation?

**Comment by helinwang** [comment]
Sorry, I can't reproduce it, maybe I get confused when seeing the trainer restarted with higher ID. Duplicate with https://github.com/PaddlePaddle/cloud/issues/319
