### ISSUE TITLE
non-fault-tolerant: got trainer id 3 when starting only 2 trainers.

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/cloud#319]
I think the third trainer got started because the previous trainer crashed. But probably the ID should be the same ID as the crashed trainer.

**Comment by typhoonzero** [comment]
Can you please run `kubectl --namespace=yournamespace get pods -a` to see if there's any crashed pods?

**Comment by Yancey1989** [comment]
I think this bug is because of we fetch the pod status from the `phase` filed, if a pod was terminated, this field is also be `Running`. Maybe we can fetch the status from `status.containerStatuses[0].state`.

**Comment by helinwang** [comment]
@typhoonzero Sorry last time I got the `admin-key.pem`, `admin.pem`, `admin.secret` and `ca.pem` from you, but I have not figured out how to use them. I searched this link https://kubernetes.io/docs/tasks/administer-cluster/share-configuration/ , but still not sure how to configure them. Could you give me some tips? :)

**Comment by Yancey1989** [comment]
With #320 has been merged, PaddleCloud does not restart the failed pod anymore with no-fault-tolerant mode.

**Comment by helinwang** [comment]
@Yancey1989 Thanks! Closing this now. Can you take a look at https://github.com/PaddlePaddle/cloud/issues/318 ?

**Comment by helinwang** [comment]
@Yancey1989 I still see no-fault-tolerant mode trainer restarted after crash, is the PR deployed to production?
