### ISSUE TITLE
The mounted path of job pod is wrong when using hostpath

### ISSUE THREAD

**Issue by m3ngyang** [PaddlePaddle/cloud#354]
When I submit a training task, job pods always crash and tell me that `No such file or directory`. Then I find that file paths do not match.
![image](https://user-images.githubusercontent.com/3349368/29697187-2c6cc996-8980-11e7-9ea1-f0ca1ce1d9c5.png)

**Comment by typhoonzero** [comment]
Change `~/.paddle/config` datacenter configuration to the cluster name you are using, `mytest` seems not a valid one.

**Comment by Yancey1989** [comment]
Maybe this is a bug for HOSTPATH mode, the `mount_path` https://github.com/PaddlePaddle/cloud/blob/develop/paddlecloud/paddlecloud/settings.py#L276 should be configured as `/host/path/%s` % usrename

**Comment by Yancey1989** [comment]
> A better choice is to download or call some API to get the file.

Agree, but maybe the `HOSTPATH` means we can use some distributed file system like NFS, GluterFS,HDFS mount host as VFS? 

And I'm sure that `CALL API` to download/uplaod files is an import feature.
