### ISSUE TITLE
Make sure fit a line works with fault tolerant mode: trainer, new pserver, master

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/cloud#401]
Please sync with @putcn about how to test it properly, and the 踩过的坑.

**Comment by putcn** [comment]
fit_a_line is not working properly event without auto-scaling, going to fix this first then test if it works with auto-scaling

**Comment by putcn** [comment]
tested with randomly killing pods during training. no issue found

**Comment by helinwang** [comment]
Thanks @putcn ! Can newly added trainers join the training?

**Comment by putcn** [comment]
yup, it did join the training
