### ISSUE TITLE
Make sure recommender_system works with fault tolerant mode: trainer, new pserver, master

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/cloud#406]
Please sync with @putcn about how to test it properly, and the 踩过的坑.

**Comment by putcn** [comment]
this demo works with minikube demo. but when change the pass number to 10 and manually kill pods, the auto-scaler stops working eventually. I think I might have something to do with error number count and timeout.
anyway, there is nothing need to be fixed in this demo per se.
