### ISSUE TITLE
trainer waits to acquire etcd lock forever when another trainer has locked

### ISSUE THREAD

**Issue by putcn** [PaddlePaddle/cloud#412]
2 trainers in my setup, and one trainer acquired etcd lock, and the other one is stuck at waiting to acquire etcd lock until the job is done

``` bash
Starting training job:  /trainings/fit_a_line, num_gradient_servers: 2, trainer_id:  0, version: 
I1019 00:12:54.638308    40 Util.cpp:166] commandline:  --num_gradient_servers=2 --ports_num_for_sparse=1 --use_gpu=0 --trainer_id=0 --trainer_count=1 --num_passes=1 --ports_num=1 --port=7164 
I1019 00:12:54.645221    40 GradientMachine.cpp:85] Initing parameters..
I1019 00:12:54.645301    40 GradientMachine.cpp:92] Init parameters done.
time="2017-10-19T00:12:54Z" level=info msg="Connected to etcd: http://10.244.71.2:2379
" 
time="2017-10-19T00:12:54Z" level=info msg="Trying to acquire lock at /init_ps/lock."
```

**Comment by putcn** [comment]
ah, looks this has been fixed by https://github.com/PaddlePaddle/Paddle/pull/4888, going to verify and close this issue.

**Comment by putcn** [comment]
verified fixed, close this issue.

**Comment by typhoonzero** [comment]
@putcn Thanks for verifying this issue, just curious, did you build a new `paddlecloud-job` image to test this?

**Comment by putcn** [comment]
@typhoonzero yes, I did build a new paddlecloud-job to verify this https://hub.docker.com/r/putcn/cloud-job/
