### ISSUE TITLE
Autoscaling cluster experiment design

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/cloud#413]
Evironment requiremnets:

- Cluster with kubernetes 1.6.x installed, best to have paddlecloud installed.
- At least 4 nodes, each node should have multiple GPUs
- Dataset prepared to recordio format and split to multiple files.

Test cases:

1. Simple: 
    - start a mnist training job with 2 pservers, 2 trainers and 1 master, `2~100` pods. Trainer will scale immediently to use maximum free resources in the cluster.
    - start another `deployment` simulating online cluster loads. Trainer should scale down if not enouph resource left.
1. Simple with GPU:
    - same to case 1, but the mnist job requests GPU resource.
1. Many Jobs
    - start `5~10` mnist training jobs with different parallelism settings, scale `2~100` pods. Jobs should scale equally and fair.
    - each time add one load to cluster, see the down scaling of the jobs.

**Comment by putcn** [comment]
👍 
can we also publish a white paper describing this experiment with the PR article?

**Comment by typhoonzero** [comment]
@putcn sure. Put this experiment in the PR article is also fine.

**Comment by Yancey1989** [comment]
- Computing Resources
  - CPU: 120 Cores
  - GPU: 8 GPU
- Experiment features:
  - Cluster resources utils, maybe we can use (requests/total) as the target
  - Job training cost time.
- Additional Test Case
  - Inference serving with 5 pods in cluster.
  - Start a training job with 100 trainers(2 pservers + 1 master)
  - Start another training job with 20 trainers ( 2 pservers  + 1 master)
  - Compare the experiment features.

**Comment by helinwang** [comment]
Some additional ideas:

We need to test the cluster running Pods other than PaddlePaddle Pods (e.g., nginx, databases), and show that the training job is scaled down when the QPS (actually CPU limit) of the nginx server increases. This use case is very good for training that only requires CPU and memory resources - share the CPU and memory with the general purpose Pods.
