### ISSUE TITLE
Cluster training pictures

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/cloud#420]
![trainer](https://user-images.githubusercontent.com/13348433/31772146-41523d84-b511-11e7-8a12-a69fd136c283.png)

**Comment by typhoonzero** [comment]
![trainer_cn](https://user-images.githubusercontent.com/13348433/31772175-5f419eca-b511-11e7-9db7-5231fe3d9ccb.png)

**Comment by saritha-infosys** [comment]
Hi,  What exactly you need to for this issue

**Comment by typhoonzero** [comment]
Sorry, forget to mention that, these pictures is for the markdown documents [here](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/usage/cluster/cluster_train_en.md)

Because sphinx seems not working with relative links in our CI. I'm closing this now.
