### ISSUE TITLE
dynamically set task timeout duration in master

### ISSUE THREAD

**Issue by putcn** [PaddlePaddle/cloud#429]
Currently, a task timeout duration is hardcoded as 20min. one improvement we can do is to set this duration dynamically. we can collect this data from the previously finished job and keep monitoring,  changing this value.

**Comment by gongweibao** [comment]
Task timeout is a command-line parameter:
```
taskTimeoutDur := flag.Duration("task-timout-dur", 20*time.Minute, "task timout duration.")
```
