### ISSUE TITLE
fault tolerant + autoscale实验方法需要更新

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/cloud#448]
实验的目标：证明开启autoscale的集群，多种场景下在以下指标优于没有autoscale的集群

- 集群整体平均资源利用率（越大越好）
- 平均每个job的执行时间（越短越好）
- 平均每个job的等待时间，从提交到开始执行（越短越好）

实验变量：是否开启autoscale(通过是否提交trainingjob resource确定)

实验不变量：
- pserver 个数
- pserver CPU
- 期望的trainer并发数
- trainer CPU
- job程序

**Comment by Yancey1989** [comment]
赞同！
补充一下
job程序都统一使用ft的任务，可以不跑普通的任务了。

另外TestCase2，使用Nginx Pod数作为变量会更可控一些，QPS有很多不确定的因素会影响实验结果。

@helinwang 怎么看？

**Comment by typhoonzero** [comment]
> 我猜测auto-scaling和非auto-scaling的结果会非常相近，原因是fault-tolerant任务不需要等待所有的trainer都ready即可开始进行训练，在集群任务已经处于满负载的情况下，两种实验结果是一样的。

可以考虑集群"资源请求>集群总资源"的场景，这样job平均等待时间会有明显区别。

> 平均每个job的执行时间（越短越好）

这个指标只要确保 autoscale的job不会大于非autoscale版本很多，因为 在autoscale时，有些job被scale down，所以平均执行时间肯定会长（满载，有空余资源时应该是一致的），pending不被算入执行时间。

这个指标也未必合理，生产环境的job一般是有优先级的，而目前的实现并没有考虑这点。指标应该是production job执行时间不超过预期。但这个目前也没有考虑。平均job执行时间指标，要不考虑增加上述说明即可？ @putcn 可以把这些描述加在文章里。

**Comment by helinwang** [comment]
> 使用Nginx Pod数作为变量会更可控一些，QPS有很多不确定的因素会影响实验结果。

我觉得可以哈，其实QPS就是为了改变nginx pod。

**Comment by helinwang** [comment]
根据这个issue讨论结果改了下design doc：https://github.com/PaddlePaddle/cloud/pull/457
