### ISSUE TITLE
Move core job management codes to controller in go

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/cloud#462]
According to previous discussions, we'd like to put job management, autoscaling, job priority scheduler to "controller", move the python implementation to go.

This change can make the website slimmer, also make the user management pluggable. Modules we should have after this changes:

- Static web pages for general information.
- Simple account management.
- ~~`paddlectl` simply cache k8s keys and storage service keys (like ceph) and talk directly to k8s api-server using "TrainingJob" resource.~~
- `controller` parse "TrainingJob" resource to paddle job, including master, pserver and trainer.
- autoscaler runs in background and scale the current jobs in cluster.
- scheduler determine how much each job can consume using some GPU priority algorithm.

**Comment by Yancey1989** [comment]
Additional feature:
1. Some preiority algorithm for different users or different namespace

> scheduler determine how much each job can consume using some GPU priority algorithm

I think this will be implemented in a new Scheduler component in k8s, that's right? Becase only scheduler will assume which node that the Pod will be running.

**Comment by typhoonzero** [comment]
> I think this will be implemented in a new Scheduler component in k8s, that's right?

That's right!

**Comment by gongweibao** [comment]
For me:
> paddlectl simply cache k8s keys and storage service keys (like ceph) and talk directly to k8s api-server using "TrainingJob" resource.
> controller parse "TrainingJob" resource to paddle job, including master, pserver and trainer.
