### ISSUE TITLE
Merge go/autoscaler into go/controller.

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/cloud#487]
The reason for separating them into two packages are:

go/controller contains the details about k8s cluster management system, in the future we could have other cluster management systems, and we can add it without changing the go/autoscaler package.

But currently we probably don't need to separate them because:

1. Currently we don't need to support cluster management system other than k8s
1. The go/autoscaler package are supposed to **not** depend on go/controller package, since it's higher level policy, and go/controller is just a cluster management system detail. But we did not do a good job, and go/autoscaler already depends on k8s detail (the resource definition are from k8s).

**Comment by typhoonzero** [comment]
So are we going to separate these two parts later?

**Comment by gongweibao** [comment]
How long does the `later` mean?^_^

**Comment by helinwang** [comment]
@typhoonzero Not planned, since we don't have any plan for supporting autoscaling on anything other than k8s.

**Comment by typhoonzero** [comment]
Agree, Indeed.
