### ISSUE TITLE
paddle cloud 镜像添加hdfs的支持

### ISSUE THREAD

**Issue by seiriosPlus** [PaddlePaddle/cloud#528]
现在有读取hdfs数据的需求，默认的cloud镜像不包含hadoop客户端，需要自己指定，每次上传都需要半个小时左右，很耗时。
希望提供一个包含hdfs客户端的镜像版本。

**Comment by Yancey1989** [comment]
Done.
The user could specify a runtime Docker image by passing the submit argument `-image registry.baidu.com/paddlepaddle/paddlecloud-job`
