### ISSUE TITLE
paddle cloud 读取hdfs上多文件问题

### ISSUE THREAD

**Issue by hyo009** [PaddlePaddle/cloud#532]
hdfs训练文件夹中有5000个文件，使用node_id = int(os.getenv("PADDLE_INIT_TRAINER_ID")),
file_id = "part-%0*d" % (5, node_id)随机遍历训练文件名。
提交任务设置变量parallelism为10，训练过程中发现只遍历了前10个文件。
请问有什么方法可以遍历训练文件夹中所有5000个文件？

**Comment by typhoonzero** [comment]
```python
node_count = int(os.getenv("PADDLE_INIT_NUM_GRADIENT_SERVERS"))
for i in xrange(5000):
    node_id = int(os.getenv("PADDLE_INIT_TRAINER_ID"))
    if i % node_count == node_id:
        # read your file
```

**Comment by hyo009** [comment]
训练文件名是part-00000至part-04999，要读取的话写file_id = "part-%0*d" % (5, node_id)还是file_id="part-0"+str(i)

**Comment by typhoonzero** [comment]
在if下面用`"part-%0*d" % (5, i)`读取

**Comment by hyo009** [comment]
尝试了，train和test的文件夹中只读取了第一个文件就训练结束。

**Comment by hyo009** [comment]
train_reader使用pipe_reader读取hdfs中的文件：
train_reader = paddle.batch(paddle.reader.shuffle(pipe_reader(gene_cmd("train"), data_reader), 
											buf_size=bs*200),batch_size=bs)
其中gene_cmd函数：
def gene_cmd(typee):
	# gene hdfs file real location
	if typee == "train":

		node_count = int(os.getenv("PADDLE_INIT_NUM_GRADIENT_SERVERS"))
		for i in xrange(3000):
			node_id = int(os.getenv("PADDLE_INIT_TRAINER_ID"))
			if i % node_count == node_id:
				file_id = "part-%0*d" % (5, node_id)
		filename = train_data_dir + file_id

	else:
		node_count = int(os.getenv("PADDLE_INIT_NUM_GRADIENT_SERVERS"))
		for i in xrange(5000):
			node_id = int(os.getenv("PADDLE_INIT_TRAINER_ID"))
			if i % node_count == node_id:
				file_id = "part-%0*d" % (5, node_id)			
		filename = test_data_dir + file_id

	command = hadoop_cmd + " " + filename

	return command

**Comment by typhoonzero** [comment]
`pipe_reader`现在只能根据一个command返回一个reader，这个需要扩展下功能，可以方便读取。目前可以先改一下pipe_reader代码：

```python

def pipe_reader(left_cmd,
                parser,
                bufsize=8192,
                file_type="plain",
                cut_lines=True,
                line_break="\n"):
    if not isinstance(left_cmd, str):
        raise TypeError("left_cmd must be a string")
    if not callable(parser):
        raise TypeError("parser must be a callable object")
    dec = zlib.decompressobj(
        32 + zlib.MAX_WBITS)  # offset 32 to skip the header

    def reader():
        node_count = int(os.getenv("PADDLE_INIT_NUM_GRADIENT_SERVERS"))
        for i in xrange(5000):
            node_id = int(os.getenv("PADDLE_INIT_TRAINER_ID"))
            if i % node_count == node_id:
                # generate left_cmd command here:
                ...
                process = subprocess.Popen(
                    left_cmd.split(" "), bufsize=bufsize, stdout=subprocess.PIPE)
                remained = ""
                while True:
                    buff = process.stdout.read(bufsize)
                    if buff:
                        if file_type == "gzip":
                            decomp_buff = dec.decompress(buff)
                        elif file_type == "plain":
                            decomp_buff = buff
                        else:
                            raise TypeError("file_type %s is not allowed" % file_type)

                        if cut_lines:
                            lines, remained = _buf2lines(''.join(
                                [remained, decomp_buff]), line_break)
                            parsed_list = parser(lines)
                            for ret in parsed_list:
                                yield ret
                        else:
                            for ret in parser(decomp_buff):
                                yield ret
                    else:
                        break

    return reader

```

**Comment by Yancey1989** [comment]
可以尝试下cmd里内嵌一个pipe，最终生成的cmd类似于：
```
${hadoop_cmd} ls file1 file2 file3 ... |xargs ${hadoop_cmd} cat
```

**Comment by typhoonzero** [comment]
这样比较麻烦，而且那个string太长了。我今天改下那个pipe_reader吧。

**Comment by hyo009** [comment]
pipe_reader改了能在这贴下或留个链接么？谢谢！

**Comment by seiriosPlus** [comment]
如果在这里写PADDLE_INIT_TRAINER_ID这几个参数的话， 能否在MPI集群上使用呢

**Comment by typhoonzero** [comment]
@hyo009 https://github.com/PaddlePaddle/Paddle/pull/6990 已经merge了，可以参考这个用法写。不更新paddle的话，可以直接把那个class copy出来用

**Comment by typhoonzero** [comment]
MPI集群上现在是类似`PADDLE_TRAINER_ID`这样的参数形式。
