### ISSUE TITLE
PFSServer

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/cloud#561]
- What does PFS mean?

- The [README.md](https://github.com/PaddlePaddle/cloud/blob/develop/go/README_CN.md) should be moved from directory `go` into the directory where PFS code resides.

**Comment by gongweibao** [comment]
- PFS means PaddleCloud File System.

> The [README.md](https://github.com/PaddlePaddle/cloud/blob/develop/go/README_CN.md) should be moved from directory `go` into the directory where PFS code resides.

OK!
