### ISSUE TITLE
Make it clear that what a training job is composed of

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/cloud#575]
- a Kubernetes job of trainers
- a Kubernetes replica set of parameter servers
- a Kubernetes replica set of the master -- we use the replica set to (1) make sure that there is one and only one master process in a job, and (2) recover it when it fails.

We might need a data type to represent this fact.

**Comment by gongweibao** [comment]
> we use the replica set to (1) make sure that there is one and only one master process in a job

we use etcd to 
(1) make sure that there is one and only one master process in a job and (2) recover it when it fails.
