### ISSUE TITLE
PADDLE_INIT_TRAINER_COUNT是指每个trainer使用的cpu或者gpu个数还是指trainer的个数？

### ISSUE THREAD

**Issue by xymyeah** [PaddlePaddle/cloud#581]
paddle_job.py中PADDLE_INIT_TRAINER_COUNT是指每个trainer使用的cpu或者gpu个数？

下面的PADDLE_INIT_TRAINER_COUNT是指trainer的个数，还是指每个trainer使用的cpu或者gpu个数？
paddle.init(
            use_gpu=use_gpu,
            trainer_count=int(os.getenv("PADDLE_INIT_TRAINER_COUNT", "1")))

**Comment by wanghaoshuang** [comment]
PADDLE_INIT_TRAINER_COUNT是指trainer的个数.

**Comment by xymyeah** [comment]
paddle_job.py中的代码
是这样的
 if self.gpu > 0:
            envs.append({"name":"PADDLE_INIT_TRAINER_COUNT", "value":str(self.gpu)})
        else:
            envs.append({"name":"PADDLE_INIT_TRAINER_COUNT", "value":str(self.cpu)})

**Comment by xymyeah** [comment]
Paddle/doc/howto/usage/cluster/src/word2vec/api_train_v2_cluster.py中是这样的
if not cluster_train:
        paddle.init(
            use_gpu=use_gpu,
            trainer_count=int(os.getenv("PADDLE_INIT_TRAINER_COUNT", "1")))
    else:
        paddle.init(
            use_gpu=use_gpu,
            trainer_count=int(os.getenv("PADDLE_INIT_TRAINER_COUNT", "1")),

这是不是矛盾呀？

**Comment by wanghaoshuang** [comment]
这里的`if...else...`判断是为了为分布式的init添加`port` `port num`等配置信息. 
在分布式情况下，`trainer_count` 是指每个node上的trainer个数？`node`的数量是由提交job的脚本指定的。

**Comment by typhoonzero** [comment]
@xymyeah @wanghaoshuang v1/v2中`trainer_count`是只单节点的线程数或GPU卡数： http://www.paddlepaddle.org/docs/develop/documentation/en/howto/usage/cluster/cluster_train_en.html#permalink-3-command-line-arguments
