### ISSUE TITLE
.travis.yml refers to nonexisting bash script

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/cloud#586]
`.travis.yml` refers to `.tools/gen_config.sh`

https://github.com/PaddlePaddle/cloud/blob/48b4261342213445eeded108612c3916d4231894/.travis.yml#L18

which doesn't seem exist in https://github.com/PaddlePaddle/cloud/tree/develop/.tools

**Comment by wangkuiyi** [comment]
It seems that in [the PR](https://github.com/PaddlePaddle/cloud/pull/148) by @gongweibao , the file .tools/gen_config.sh was moved into [`go/.tools/gen_config.sh`](https://github.com/PaddlePaddle/cloud/tree/develop/go/.tools)

**Comment by gongweibao** [comment]
Yep.

**Comment by wangkuiyi** [comment]
https://github.com/PaddlePaddle/cloud/blob/develop/go/.tools/gen_config.sh

What is the purpose of this shell script? Is it necessary?
