### ISSUE TITLE
Rewrite root README.md file

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/cloud#591]
List componenets:

1. paddlectrl (Go)
1. paddlecloud (Python)
1. paddlefs (PFS, Go)
1. EDL controller (Go)

Add a figure to explain how these components interact with each other. https://github.com/PaddlePaddle/cloud/issues/593

**Comment by typhoonzero** [comment]
I suppose the root `README.md` have the following structure:

- Introduction
  - What this repo does, what it contains, what kind of ability can users get from this repo.
- Components
  - client: paddlectl
  - paddlecloud server
  - paddlefs
  - EDL
- User Manuals
  - link to the tutorial
  - command line reference
  - FAQs
- Build
  - link to build EDL
  - link to build EDL controller image
  - build paddlecloud-job docker image
  - build paddlectl
- Deploy
  - link to deploy paddlecloud
  - link to deploy EDL
  - link to deploy on minikube
- Contribute
    How to contribute code. link to code structure and design docs.

**Comment by Yancey1989** [comment]
Add items:

- Deploy
  - Link to deploy PaddleFS server
- User Manuals
  - link to the benchmark

**Comment by gongweibao** [comment]
Maybe we can add develop-guide like [this](https://github.com/tensorflow/k8s/blob/master/developer_guide.md)

**Comment by typhoonzero** [comment]
Awesome, will update the PR.
