### ISSUE TITLE
[WIP]Move glide.yaml and glide.lock to the top directory

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/cloud#615]
This could be helpful that we can run `glide install -v` directly under the top-level directory, then the `vendor` directory is not created inside `go` folder which could be annoying.

**Comment by gongweibao** [comment]
Since we have many modules under `cloud` project and it could be confusing to set `glide` only for Go.

**Comment by typhoonzero** [comment]
I think it's OK? The main programming language is Go, and if we move `glide.yaml` to root folder, the `vender` folder will be created here when building which is easier to manage.
