### ISSUE TITLE
Paddle cloud job Docker image with secret registry server

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/cloud#63]
For now, Paddle cloud job Docker image is pulled from Docker hub, but the internal Kubernetes cluster, the node can only pull Docker image from a secret registry server, so we should configure the secret of Docker registry in `settings.py` and Kubernetes Job/Replicaset YAML .

**Comment by typhoonzero** [comment]
We need a public registry to store cluster job base images. So that pull will not be restricted.

**Comment by Yancey1989** [comment]
@typhoonzero public registry is a good choice, but sometimes we don't the access, so I think maybe it's an optional configuration.
