### ISSUE TITLE
使用file put 命令上传大数据模型的时候，会报错out of memory，使用cp上传文件目录的时候，会上传成文件

### ISSUE THREAD

**Issue by qdq2014** [PaddlePaddle/cloud#636]
目录/pfs/dlnel/home/songqingyun@baidu.com/data/preprocessed/testset/
文件大小728657261B

**Comment by qdq2014** [comment]
本地目录/home/work/local/qiudeqiang/dureader/DuReader-master/data/preprocessed/testset
上传命令paddlecloud cp /home/work/local/qiudeqiang/dureader/DuReader-master/data/preprocessed/testset /pfs/dlnel/home/songqingyun@baidu.com/data/preprocessed/testset 
会提示
[INFO]  Uploaded /home/work/local/qiudeqiang/dureader/DuReader-master/data/preprocessed/devset/search.dev.json
[INFO]  Uploaded /home/work/local/qiudeqiang/dureader/DuReader-master/data/preprocessed/devset/zhidao.dev.json
但是paddlecloud file ls  /pfs/dlnel/home/songqingyun@baidu.com/data/preprocessed/devset 
ls file error: server error: 500 Internal Server Error
因为上传成了文件

**Comment by gongweibao** [comment]
Solved offline.
