### ISSUE TITLE
fail to submit to mulan datacenter

### ISSUE THREAD

**Issue by April0402** [PaddlePaddle/cloud#640]
This is my submit code:

`paddlecloud submit \`
`-jobname $job_name \`
`-cpu 1 \`
`-gpu 1 \`
`-memory 25Gi \`
`-parallelism 1 \`
`-pscpu 1 \`
`-pservers 1 \`
`-psmemory 1Gi \`
`-entry "sh run.sh aaa" \`
`package`

This is error info

Uploading ... /home/disk1/lishuangjie/open_predicate/bin/predict_by_dnn/predict/ttt.get_data/package/run.sh /pfs/mulan/home/lishuangjie@baidu.com/jobs/sys-cmd/run.sh
previous token not found, fetching a new one...
error submiting job: package not exist in cloud: /pfs//jobs/sys-cmd

**Comment by seiriosPlus** [comment]
change the submit code -cpu 1  to -cpu 0 may fix it.
we will fix cloud tips about this case.
